<?php

namespace QuizzyBundle\Repository;

/**
 * AnswerCompletionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerCompletionRepository extends \Doctrine\ORM\EntityRepository
{
}
