<?php

namespace QuizzyBundle\Repository;

use QuizzyBundle\Entity\User;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param User $user
     * @return array
     */
    public function getFriendsByUser(User $user)
    {
        $dql = "
            SELECT f
            FROM QuizzyBundle:Friend f
            WHERE f.accepted = TRUE
            AND (f.user_sender = :user OR f.user = :user)
        ";

        $query = $this->_em->createQuery($dql);
        $query->setParameter('user', $user);
        return $query->getResult();
    }

    /**
     * @param User $currentUser
     * @param User $user
     * @return mixed
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getFriend(User $currentUser, User $user)
    {
        $dql = "
            SELECT f
            FROM QuizzyBundle:Friend f
            WHERE f.user_sender = :currentUser AND f.user = :user
            OR f.user_sender = :user AND f.user = :currentUser
        ";

        $query = $this->_em->createQuery($dql);
        $query->setParameter('currentUser', $currentUser);
        $query->setParameter('user', $user);
        return $query->getSingleResult();
    }

    /**
     * @param User $user
     * @return array
     */
    public function getFriendsRequestByUser(User $user)
    {
        $dql = "
            SELECT f
            FROM QuizzyBundle:Friend f
            WHERE f.user = :user
            AND f.accepted = FALSE
        ";

        $query = $this->_em->createQuery($dql);
        $query->setParameter('user', $user);
        return $query->getResult();
    }
}
