<?php

namespace QuizzyBundle\Repository;

/**
 * PartCompletionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartCompletionRepository extends \Doctrine\ORM\EntityRepository
{
}
