<?php

namespace QuizzyBundle\Repository;

/**
 * QuestionCompletionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionCompletionRepository extends \Doctrine\ORM\EntityRepository
{
}
