<?php

namespace QuizzyBundle\Repository;

/**
 * QuizCompletionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizCompletionRepository extends \Doctrine\ORM\EntityRepository
{
}
